// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: au/com/codeka/warworlds/common/proto/empire.proto at 8:1
package au.com.codeka.warworlds.common.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 *
 * Details of an empire's rank (such as number of ships, number of colonies etc)
 */
public final class EmpireRank extends Message<EmpireRank, EmpireRank.Builder> {
  public static final ProtoAdapter<EmpireRank> ADAPTER = new ProtoAdapter_EmpireRank();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_EMPIRE_ID = 0L;

  public static final Integer DEFAULT_RANK = 0;

  public static final Integer DEFAULT_LAST_RANK = 0;

  public static final Integer DEFAULT_TOTAL_STARS = 0;

  public static final Integer DEFAULT_TOTAL_COLONIES = 0;

  public static final Integer DEFAULT_TOTAL_SHIPS = 0;

  public static final Integer DEFAULT_TOTAL_BUILDINGS = 0;

  public static final Integer DEFAULT_TOTAL_POPULATION = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long empire_id;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer rank;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer last_rank;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer total_stars;

  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer total_colonies;

  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer total_ships;

  @WireField(
      tag = 7,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer total_buildings;

  @WireField(
      tag = 8,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer total_population;

  public EmpireRank(Long empire_id, Integer rank, Integer last_rank, Integer total_stars, Integer total_colonies, Integer total_ships, Integer total_buildings, Integer total_population) {
    this(empire_id, rank, last_rank, total_stars, total_colonies, total_ships, total_buildings, total_population, ByteString.EMPTY);
  }

  public EmpireRank(Long empire_id, Integer rank, Integer last_rank, Integer total_stars, Integer total_colonies, Integer total_ships, Integer total_buildings, Integer total_population, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.empire_id = empire_id;
    this.rank = rank;
    this.last_rank = last_rank;
    this.total_stars = total_stars;
    this.total_colonies = total_colonies;
    this.total_ships = total_ships;
    this.total_buildings = total_buildings;
    this.total_population = total_population;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.empire_id = empire_id;
    builder.rank = rank;
    builder.last_rank = last_rank;
    builder.total_stars = total_stars;
    builder.total_colonies = total_colonies;
    builder.total_ships = total_ships;
    builder.total_buildings = total_buildings;
    builder.total_population = total_population;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof EmpireRank)) return false;
    EmpireRank o = (EmpireRank) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(empire_id, o.empire_id)
        && Internal.equals(rank, o.rank)
        && Internal.equals(last_rank, o.last_rank)
        && Internal.equals(total_stars, o.total_stars)
        && Internal.equals(total_colonies, o.total_colonies)
        && Internal.equals(total_ships, o.total_ships)
        && Internal.equals(total_buildings, o.total_buildings)
        && Internal.equals(total_population, o.total_population);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (empire_id != null ? empire_id.hashCode() : 0);
      result = result * 37 + (rank != null ? rank.hashCode() : 0);
      result = result * 37 + (last_rank != null ? last_rank.hashCode() : 0);
      result = result * 37 + (total_stars != null ? total_stars.hashCode() : 0);
      result = result * 37 + (total_colonies != null ? total_colonies.hashCode() : 0);
      result = result * 37 + (total_ships != null ? total_ships.hashCode() : 0);
      result = result * 37 + (total_buildings != null ? total_buildings.hashCode() : 0);
      result = result * 37 + (total_population != null ? total_population.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (empire_id != null) builder.append(", empire_id=").append(empire_id);
    if (rank != null) builder.append(", rank=").append(rank);
    if (last_rank != null) builder.append(", last_rank=").append(last_rank);
    if (total_stars != null) builder.append(", total_stars=").append(total_stars);
    if (total_colonies != null) builder.append(", total_colonies=").append(total_colonies);
    if (total_ships != null) builder.append(", total_ships=").append(total_ships);
    if (total_buildings != null) builder.append(", total_buildings=").append(total_buildings);
    if (total_population != null) builder.append(", total_population=").append(total_population);
    return builder.replace(0, 2, "EmpireRank{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<EmpireRank, Builder> {
    public Long empire_id;

    public Integer rank;

    public Integer last_rank;

    public Integer total_stars;

    public Integer total_colonies;

    public Integer total_ships;

    public Integer total_buildings;

    public Integer total_population;

    public Builder() {
    }

    public Builder empire_id(Long empire_id) {
      this.empire_id = empire_id;
      return this;
    }

    public Builder rank(Integer rank) {
      this.rank = rank;
      return this;
    }

    public Builder last_rank(Integer last_rank) {
      this.last_rank = last_rank;
      return this;
    }

    public Builder total_stars(Integer total_stars) {
      this.total_stars = total_stars;
      return this;
    }

    public Builder total_colonies(Integer total_colonies) {
      this.total_colonies = total_colonies;
      return this;
    }

    public Builder total_ships(Integer total_ships) {
      this.total_ships = total_ships;
      return this;
    }

    public Builder total_buildings(Integer total_buildings) {
      this.total_buildings = total_buildings;
      return this;
    }

    public Builder total_population(Integer total_population) {
      this.total_population = total_population;
      return this;
    }

    @Override
    public EmpireRank build() {
      return new EmpireRank(empire_id, rank, last_rank, total_stars, total_colonies, total_ships, total_buildings, total_population, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_EmpireRank extends ProtoAdapter<EmpireRank> {
    ProtoAdapter_EmpireRank() {
      super(FieldEncoding.LENGTH_DELIMITED, EmpireRank.class);
    }

    @Override
    public int encodedSize(EmpireRank value) {
      return (value.empire_id != null ? ProtoAdapter.INT64.encodedSizeWithTag(1, value.empire_id) : 0)
          + (value.rank != null ? ProtoAdapter.INT32.encodedSizeWithTag(2, value.rank) : 0)
          + (value.last_rank != null ? ProtoAdapter.INT32.encodedSizeWithTag(3, value.last_rank) : 0)
          + (value.total_stars != null ? ProtoAdapter.INT32.encodedSizeWithTag(4, value.total_stars) : 0)
          + (value.total_colonies != null ? ProtoAdapter.INT32.encodedSizeWithTag(5, value.total_colonies) : 0)
          + (value.total_ships != null ? ProtoAdapter.INT32.encodedSizeWithTag(6, value.total_ships) : 0)
          + (value.total_buildings != null ? ProtoAdapter.INT32.encodedSizeWithTag(7, value.total_buildings) : 0)
          + (value.total_population != null ? ProtoAdapter.INT32.encodedSizeWithTag(8, value.total_population) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, EmpireRank value) throws IOException {
      if (value.empire_id != null) ProtoAdapter.INT64.encodeWithTag(writer, 1, value.empire_id);
      if (value.rank != null) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.rank);
      if (value.last_rank != null) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.last_rank);
      if (value.total_stars != null) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.total_stars);
      if (value.total_colonies != null) ProtoAdapter.INT32.encodeWithTag(writer, 5, value.total_colonies);
      if (value.total_ships != null) ProtoAdapter.INT32.encodeWithTag(writer, 6, value.total_ships);
      if (value.total_buildings != null) ProtoAdapter.INT32.encodeWithTag(writer, 7, value.total_buildings);
      if (value.total_population != null) ProtoAdapter.INT32.encodeWithTag(writer, 8, value.total_population);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public EmpireRank decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.empire_id(ProtoAdapter.INT64.decode(reader)); break;
          case 2: builder.rank(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.last_rank(ProtoAdapter.INT32.decode(reader)); break;
          case 4: builder.total_stars(ProtoAdapter.INT32.decode(reader)); break;
          case 5: builder.total_colonies(ProtoAdapter.INT32.decode(reader)); break;
          case 6: builder.total_ships(ProtoAdapter.INT32.decode(reader)); break;
          case 7: builder.total_buildings(ProtoAdapter.INT32.decode(reader)); break;
          case 8: builder.total_population(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public EmpireRank redact(EmpireRank value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
