// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: au/com/codeka/warworlds/common/proto/empire.proto at 19:1
package au.com.codeka.warworlds.common.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class EmpireRanks extends Message<EmpireRanks, EmpireRanks.Builder> {
  public static final ProtoAdapter<EmpireRanks> ADAPTER = new ProtoAdapter_EmpireRanks();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_DATE = 0L;

  @WireField(
      tag = 1,
      adapter = "au.com.codeka.warworlds.common.proto.EmpireRank#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<EmpireRank> ranks;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long date;

  public EmpireRanks(List<EmpireRank> ranks, Long date) {
    this(ranks, date, ByteString.EMPTY);
  }

  public EmpireRanks(List<EmpireRank> ranks, Long date, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.ranks = Internal.immutableCopyOf("ranks", ranks);
    this.date = date;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.ranks = Internal.copyOf("ranks", ranks);
    builder.date = date;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof EmpireRanks)) return false;
    EmpireRanks o = (EmpireRanks) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(ranks, o.ranks)
        && Internal.equals(date, o.date);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (ranks != null ? ranks.hashCode() : 1);
      result = result * 37 + (date != null ? date.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (ranks != null) builder.append(", ranks=").append(ranks);
    if (date != null) builder.append(", date=").append(date);
    return builder.replace(0, 2, "EmpireRanks{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<EmpireRanks, Builder> {
    public List<EmpireRank> ranks;

    public Long date;

    public Builder() {
      ranks = Internal.newMutableList();
    }

    public Builder ranks(List<EmpireRank> ranks) {
      Internal.checkElementsNotNull(ranks);
      this.ranks = ranks;
      return this;
    }

    public Builder date(Long date) {
      this.date = date;
      return this;
    }

    @Override
    public EmpireRanks build() {
      return new EmpireRanks(ranks, date, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_EmpireRanks extends ProtoAdapter<EmpireRanks> {
    ProtoAdapter_EmpireRanks() {
      super(FieldEncoding.LENGTH_DELIMITED, EmpireRanks.class);
    }

    @Override
    public int encodedSize(EmpireRanks value) {
      return EmpireRank.ADAPTER.asRepeated().encodedSizeWithTag(1, value.ranks)
          + (value.date != null ? ProtoAdapter.INT64.encodedSizeWithTag(2, value.date) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, EmpireRanks value) throws IOException {
      if (value.ranks != null) EmpireRank.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.ranks);
      if (value.date != null) ProtoAdapter.INT64.encodeWithTag(writer, 2, value.date);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public EmpireRanks decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.ranks.add(EmpireRank.ADAPTER.decode(reader)); break;
          case 2: builder.date(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public EmpireRanks redact(EmpireRanks value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.ranks, EmpireRank.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
