// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: au/com/codeka/warworlds/common/proto/packets.proto at 20:1
package au.com.codeka.warworlds.common.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * The "hello" packet that's sent by the client when it first connects to the game socket.
 */
public final class HelloPacket extends Message<HelloPacket, HelloPacket.Builder> {
  public static final ProtoAdapter<HelloPacket> ADAPTER = new ProtoAdapter_HelloPacket();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_EMPIRE_ID = 0L;

  public static final Long DEFAULT_OUR_STAR_LAST_SIMULATION = 0L;

  public static final Long DEFAULT_LAST_CHAT_TIME = 0L;

  /**
   * The ID of the empire you're connecting as. You should already know this from the response to
   * the login request.
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long empire_id;

  /**
   * The most recent "last_simulation" time we have for any of our stars. The server will send us
   * an update on all of our stars with a last_simulation newer than this value. This does mean
   * that any stars that *were* ours before this simulation but are no longer ours will simply
   * not be updated, but that's probably acceptable.
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long our_star_last_simulation;

  /**
   * The most time of the recent chat message that we have stored. We'll send you all the chat
   * messages that you should've seen that's newer than this.
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long last_chat_time;

  public HelloPacket(Long empire_id, Long our_star_last_simulation, Long last_chat_time) {
    this(empire_id, our_star_last_simulation, last_chat_time, ByteString.EMPTY);
  }

  public HelloPacket(Long empire_id, Long our_star_last_simulation, Long last_chat_time, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.empire_id = empire_id;
    this.our_star_last_simulation = our_star_last_simulation;
    this.last_chat_time = last_chat_time;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.empire_id = empire_id;
    builder.our_star_last_simulation = our_star_last_simulation;
    builder.last_chat_time = last_chat_time;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof HelloPacket)) return false;
    HelloPacket o = (HelloPacket) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(empire_id, o.empire_id)
        && Internal.equals(our_star_last_simulation, o.our_star_last_simulation)
        && Internal.equals(last_chat_time, o.last_chat_time);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (empire_id != null ? empire_id.hashCode() : 0);
      result = result * 37 + (our_star_last_simulation != null ? our_star_last_simulation.hashCode() : 0);
      result = result * 37 + (last_chat_time != null ? last_chat_time.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (empire_id != null) builder.append(", empire_id=").append(empire_id);
    if (our_star_last_simulation != null) builder.append(", our_star_last_simulation=").append(our_star_last_simulation);
    if (last_chat_time != null) builder.append(", last_chat_time=").append(last_chat_time);
    return builder.replace(0, 2, "HelloPacket{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<HelloPacket, Builder> {
    public Long empire_id;

    public Long our_star_last_simulation;

    public Long last_chat_time;

    public Builder() {
    }

    /**
     * The ID of the empire you're connecting as. You should already know this from the response to
     * the login request.
     */
    public Builder empire_id(Long empire_id) {
      this.empire_id = empire_id;
      return this;
    }

    /**
     * The most recent "last_simulation" time we have for any of our stars. The server will send us
     * an update on all of our stars with a last_simulation newer than this value. This does mean
     * that any stars that *were* ours before this simulation but are no longer ours will simply
     * not be updated, but that's probably acceptable.
     */
    public Builder our_star_last_simulation(Long our_star_last_simulation) {
      this.our_star_last_simulation = our_star_last_simulation;
      return this;
    }

    /**
     * The most time of the recent chat message that we have stored. We'll send you all the chat
     * messages that you should've seen that's newer than this.
     */
    public Builder last_chat_time(Long last_chat_time) {
      this.last_chat_time = last_chat_time;
      return this;
    }

    @Override
    public HelloPacket build() {
      return new HelloPacket(empire_id, our_star_last_simulation, last_chat_time, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_HelloPacket extends ProtoAdapter<HelloPacket> {
    ProtoAdapter_HelloPacket() {
      super(FieldEncoding.LENGTH_DELIMITED, HelloPacket.class);
    }

    @Override
    public int encodedSize(HelloPacket value) {
      return (value.empire_id != null ? ProtoAdapter.INT64.encodedSizeWithTag(1, value.empire_id) : 0)
          + (value.our_star_last_simulation != null ? ProtoAdapter.INT64.encodedSizeWithTag(2, value.our_star_last_simulation) : 0)
          + (value.last_chat_time != null ? ProtoAdapter.INT64.encodedSizeWithTag(3, value.last_chat_time) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, HelloPacket value) throws IOException {
      if (value.empire_id != null) ProtoAdapter.INT64.encodeWithTag(writer, 1, value.empire_id);
      if (value.our_star_last_simulation != null) ProtoAdapter.INT64.encodeWithTag(writer, 2, value.our_star_last_simulation);
      if (value.last_chat_time != null) ProtoAdapter.INT64.encodeWithTag(writer, 3, value.last_chat_time);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public HelloPacket decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.empire_id(ProtoAdapter.INT64.decode(reader)); break;
          case 2: builder.our_star_last_simulation(ProtoAdapter.INT64.decode(reader)); break;
          case 3: builder.last_chat_time(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public HelloPacket redact(HelloPacket value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
