package au.com.codeka.warworlds.game.starfield;

import org.andengine.entity.Entity;
import org.andengine.entity.sprite.Sprite;
import org.andengine.opengl.texture.region.ITextureRegion;
import org.andengine.opengl.vbo.VertexBufferObjectManager;

/**
 * This entity is used to display the tactical "overlay" that is used to color the space around
 * stars owned by an empire.
 *
 * It takes the texture generated by {@link TacticalBitmapTextureSource} and applies a bit of a blur
 * to it.
 */
public class TacticalOverlayEntity extends Entity {
  private Sprite sprite;

  public TacticalOverlayEntity(float x, float y, float width, float height,
      ITextureRegion textureRegion, VertexBufferObjectManager vertexBufferObjectManager) {
    super(0, 0, 1, 1);

    sprite = new Sprite(x, y, width, height, textureRegion, vertexBufferObjectManager);
    attachChild(sprite);
  }

  @Override
  public void setAlpha(float alpha) {
    sprite.setAlpha(alpha);
  }

  @Override
  public void setColor(float r, float g, float b) {
    sprite.setColor(r, g, b);
  }
}
