// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./messages.proto
package au.com.codeka.common.model;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class ChatMessages extends Message {

  public static final List<ChatMessage> DEFAULT_MESSAGES = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public List<ChatMessage> messages;

  private ChatMessages(Builder builder) {
    super(builder);
    this.messages = immutableCopyOf(builder.messages);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ChatMessages)) return false;
    return equals(messages, ((ChatMessages) other).messages);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = messages != null ? messages.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<ChatMessages> {

    public List<ChatMessage> messages;

    public Builder() {
    }

    public Builder(ChatMessages message) {
      super(message);
      if (message == null) return;
      this.messages = copyOf(message.messages);
    }

    public Builder messages(List<ChatMessage> messages) {
      this.messages = messages;
      return this;
    }

    @Override
    public ChatMessages build() {
      return new ChatMessages(this);
    }
  }
}
