// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./messages.proto
package au.com.codeka.common.model;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;

public final class EmpireRank extends Message {

  public static final String DEFAULT_EMPIRE_KEY = "";
  public static final Integer DEFAULT_RANK = 0;
  public static final Integer DEFAULT_LAST_RANK = 0;
  public static final Integer DEFAULT_TOTAL_STARS = 0;
  public static final Integer DEFAULT_TOTAL_COLONIES = 0;
  public static final Integer DEFAULT_TOTAL_SHIPS = 0;
  public static final Integer DEFAULT_TOTAL_BUILDINGS = 0;
  public static final Integer DEFAULT_TOTAL_POPULATION = 0;

  @ProtoField(tag = 1, type = STRING)
  public String empire_key;

  @ProtoField(tag = 2, type = INT32)
  public Integer rank;

  @ProtoField(tag = 3, type = INT32)
  public Integer last_rank;

  @ProtoField(tag = 4, type = INT32)
  public Integer total_stars;

  @ProtoField(tag = 5, type = INT32)
  public Integer total_colonies;

  @ProtoField(tag = 6, type = INT32)
  public Integer total_ships;

  @ProtoField(tag = 7, type = INT32)
  public Integer total_buildings;

  @ProtoField(tag = 8, type = INT32)
  public Integer total_population;

  private EmpireRank(Builder builder) {
    super(builder);
    this.empire_key = builder.empire_key;
    this.rank = builder.rank;
    this.last_rank = builder.last_rank;
    this.total_stars = builder.total_stars;
    this.total_colonies = builder.total_colonies;
    this.total_ships = builder.total_ships;
    this.total_buildings = builder.total_buildings;
    this.total_population = builder.total_population;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof EmpireRank)) return false;
    EmpireRank o = (EmpireRank) other;
    return equals(empire_key, o.empire_key)
        && equals(rank, o.rank)
        && equals(last_rank, o.last_rank)
        && equals(total_stars, o.total_stars)
        && equals(total_colonies, o.total_colonies)
        && equals(total_ships, o.total_ships)
        && equals(total_buildings, o.total_buildings)
        && equals(total_population, o.total_population);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = empire_key != null ? empire_key.hashCode() : 0;
      result = result * 37 + (rank != null ? rank.hashCode() : 0);
      result = result * 37 + (last_rank != null ? last_rank.hashCode() : 0);
      result = result * 37 + (total_stars != null ? total_stars.hashCode() : 0);
      result = result * 37 + (total_colonies != null ? total_colonies.hashCode() : 0);
      result = result * 37 + (total_ships != null ? total_ships.hashCode() : 0);
      result = result * 37 + (total_buildings != null ? total_buildings.hashCode() : 0);
      result = result * 37 + (total_population != null ? total_population.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<EmpireRank> {

    public String empire_key;
    public Integer rank;
    public Integer last_rank;
    public Integer total_stars;
    public Integer total_colonies;
    public Integer total_ships;
    public Integer total_buildings;
    public Integer total_population;

    public Builder() {
    }

    public Builder(EmpireRank message) {
      super(message);
      if (message == null) return;
      this.empire_key = message.empire_key;
      this.rank = message.rank;
      this.last_rank = message.last_rank;
      this.total_stars = message.total_stars;
      this.total_colonies = message.total_colonies;
      this.total_ships = message.total_ships;
      this.total_buildings = message.total_buildings;
      this.total_population = message.total_population;
    }

    public Builder empire_key(String empire_key) {
      this.empire_key = empire_key;
      return this;
    }

    public Builder rank(Integer rank) {
      this.rank = rank;
      return this;
    }

    public Builder last_rank(Integer last_rank) {
      this.last_rank = last_rank;
      return this;
    }

    public Builder total_stars(Integer total_stars) {
      this.total_stars = total_stars;
      return this;
    }

    public Builder total_colonies(Integer total_colonies) {
      this.total_colonies = total_colonies;
      return this;
    }

    public Builder total_ships(Integer total_ships) {
      this.total_ships = total_ships;
      return this;
    }

    public Builder total_buildings(Integer total_buildings) {
      this.total_buildings = total_buildings;
      return this;
    }

    public Builder total_population(Integer total_population) {
      this.total_population = total_population;
      return this;
    }

    @Override
    public EmpireRank build() {
      return new EmpireRank(this);
    }
  }
}
