// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./messages.proto
package au.com.codeka.common.model;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REPEATED;

public final class EmpireRanks extends Message {

  public static final List<EmpireRank> DEFAULT_RANKS = Collections.emptyList();
  public static final Long DEFAULT_DATE = 0L;

  @ProtoField(tag = 1, label = REPEATED)
  public List<EmpireRank> ranks;

  @ProtoField(tag = 2, type = INT64)
  public Long date;

  private EmpireRanks(Builder builder) {
    super(builder);
    this.ranks = copyOf(builder.ranks);
    this.date = builder.date;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof EmpireRanks)) return false;
    EmpireRanks o = (EmpireRanks) other;
    return equals(ranks, o.ranks)
        && equals(date, o.date);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = ranks != null ? ranks.hashCode() : 0;
      result = result * 37 + (date != null ? date.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<EmpireRanks> {

    public List<EmpireRank> ranks;
    public Long date;

    public Builder() {
    }

    public Builder(EmpireRanks message) {
      super(message);
      if (message == null) return;
      this.ranks = copyOf(message.ranks);
      this.date = message.date;
    }

    public Builder ranks(List<EmpireRank> ranks) {
      this.ranks = ranks;
      return this;
    }

    public Builder date(Long date) {
      this.date = date;
      return this;
    }

    @Override
    public EmpireRanks build() {
      return new EmpireRanks(this);
    }
  }
}
