// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./messages.proto
package au.com.codeka.common.model;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoEnum;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;

public final class FleetOrder extends Message {

  public static final FLEET_ORDER DEFAULT_ORDER = FLEET_ORDER.SPLIT;
  public static final Integer DEFAULT_SPLIT_LEFT = 0;
  public static final Integer DEFAULT_SPLIT_RIGHT = 0;
  public static final String DEFAULT_STAR_KEY = "";
  public static final Fleet.FLEET_STANCE DEFAULT_STANCE = Fleet.FLEET_STANCE.PASSIVE;
  public static final String DEFAULT_MERGE_FLEET_KEY = "";

  @ProtoField(tag = 1, type = ENUM)
  public FLEET_ORDER order;

  /**
   * if the order is to split, this will be the number of ships
   * in the "left" and "right" fleets. The numbers must add up to
   * the original number of ships you had.
   */
  @ProtoField(tag = 2, type = INT32)
  public Integer split_left;

  @ProtoField(tag = 3, type = INT32)
  public Integer split_right;

  /**
   * when moving or attacking, this represents the destination star
   */
  @ProtoField(tag = 4, type = STRING)
  public String star_key;

  /**
   * if the order is SET_STANCE, this will be the stance we want to change to
   */
  @ProtoField(tag = 5, type = ENUM)
  public Fleet.FLEET_STANCE stance;

  /**
   * if the order is MERGE, this will be the fleet to merge with
   */
  @ProtoField(tag = 6, type = STRING)
  public String merge_fleet_key;

  private FleetOrder(Builder builder) {
    super(builder);
    this.order = builder.order;
    this.split_left = builder.split_left;
    this.split_right = builder.split_right;
    this.star_key = builder.star_key;
    this.stance = builder.stance;
    this.merge_fleet_key = builder.merge_fleet_key;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof FleetOrder)) return false;
    FleetOrder o = (FleetOrder) other;
    return equals(order, o.order)
        && equals(split_left, o.split_left)
        && equals(split_right, o.split_right)
        && equals(star_key, o.star_key)
        && equals(stance, o.stance)
        && equals(merge_fleet_key, o.merge_fleet_key);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = order != null ? order.hashCode() : 0;
      result = result * 37 + (split_left != null ? split_left.hashCode() : 0);
      result = result * 37 + (split_right != null ? split_right.hashCode() : 0);
      result = result * 37 + (star_key != null ? star_key.hashCode() : 0);
      result = result * 37 + (stance != null ? stance.hashCode() : 0);
      result = result * 37 + (merge_fleet_key != null ? merge_fleet_key.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<FleetOrder> {

    public FLEET_ORDER order;
    public Integer split_left;
    public Integer split_right;
    public String star_key;
    public Fleet.FLEET_STANCE stance;
    public String merge_fleet_key;

    public Builder() {
    }

    public Builder(FleetOrder message) {
      super(message);
      if (message == null) return;
      this.order = message.order;
      this.split_left = message.split_left;
      this.split_right = message.split_right;
      this.star_key = message.star_key;
      this.stance = message.stance;
      this.merge_fleet_key = message.merge_fleet_key;
    }

    public Builder order(FLEET_ORDER order) {
      this.order = order;
      return this;
    }

    public Builder split_left(Integer split_left) {
      this.split_left = split_left;
      return this;
    }

    public Builder split_right(Integer split_right) {
      this.split_right = split_right;
      return this;
    }

    public Builder star_key(String star_key) {
      this.star_key = star_key;
      return this;
    }

    public Builder stance(Fleet.FLEET_STANCE stance) {
      this.stance = stance;
      return this;
    }

    public Builder merge_fleet_key(String merge_fleet_key) {
      this.merge_fleet_key = merge_fleet_key;
      return this;
    }

    @Override
    public FleetOrder build() {
      return new FleetOrder(this);
    }
  }

  public enum FLEET_ORDER {
    @ProtoEnum(1)
    SPLIT,
    @ProtoEnum(2)
    MERGE,
    @ProtoEnum(3)
    MOVE,
    @ProtoEnum(5)
    SET_STANCE,
  }
}
