// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./messages.proto
package au.com.codeka.common.model;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class Sectors extends Message {

  public static final List<Sector> DEFAULT_SECTORS = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public List<Sector> sectors;

  private Sectors(Builder builder) {
    super(builder);
    this.sectors = copyOf(builder.sectors);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Sectors)) return false;
    return equals(sectors, ((Sectors) other).sectors);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = sectors != null ? sectors.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<Sectors> {

    public List<Sector> sectors;

    public Builder() {
    }

    public Builder(Sectors message) {
      super(message);
      if (message == null) return;
      this.sectors = copyOf(message.sectors);
    }

    public Builder sectors(List<Sector> sectors) {
      this.sectors = sectors;
      return this;
    }

    @Override
    public Sectors build() {
      return new Sectors(this);
    }
  }
}
