// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./messages.proto
package au.com.codeka.common.protobuf;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.INT32;

/**
 *
 * Refers to a participant of a chat conversation.
 */
public final class ChatConversationParticipant extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_EMPIRE_ID = 0;
  public static final Boolean DEFAULT_IS_MUTED = false;

  @ProtoField(tag = 1, type = INT32)
  public Integer empire_id;

  @ProtoField(tag = 2, type = BOOL)
  public Boolean is_muted;

  public ChatConversationParticipant() {
  }

  public ChatConversationParticipant(Integer empire_id, Boolean is_muted) {
    this.empire_id = empire_id;
    this.is_muted = is_muted;
  }

  private ChatConversationParticipant(Builder builder) {
    this(builder.empire_id, builder.is_muted);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ChatConversationParticipant)) return false;
    ChatConversationParticipant o = (ChatConversationParticipant) other;
    return equals(empire_id, o.empire_id)
        && equals(is_muted, o.is_muted);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = empire_id != null ? empire_id.hashCode() : 0;
      result = result * 37 + (is_muted != null ? is_muted.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ChatConversationParticipant> {

    public Integer empire_id;
    public Boolean is_muted;

    public Builder() {
    }

    public Builder(ChatConversationParticipant message) {
      super(message);
      if (message == null) return;
      this.empire_id = message.empire_id;
      this.is_muted = message.is_muted;
    }

    public Builder empire_id(Integer empire_id) {
      this.empire_id = empire_id;
      return this;
    }

    public Builder is_muted(Boolean is_muted) {
      this.is_muted = is_muted;
      return this;
    }

    @Override
    public ChatConversationParticipant build() {
      return new ChatConversationParticipant(this);
    }
  }
}
