// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./messages.proto
package au.com.codeka.common.protobuf;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

/**
 *
 * A collection of Colonies
 */
public final class Colonies extends Message {
  private static final long serialVersionUID = 0L;

  public static final List<Colony> DEFAULT_COLONIES = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED, messageType = Colony.class)
  public final List<Colony> colonies;

  public Colonies(List<Colony> colonies) {
    this.colonies = immutableCopyOf(colonies);
  }

  private Colonies(Builder builder) {
    this(builder.colonies);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Colonies)) return false;
    return equals(colonies, ((Colonies) other).colonies);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = colonies != null ? colonies.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<Colonies> {

    public List<Colony> colonies;

    public Builder() {
    }

    public Builder(Colonies message) {
      super(message);
      if (message == null) return;
      this.colonies = copyOf(message.colonies);
    }

    public Builder colonies(List<Colony> colonies) {
      this.colonies = checkForNulls(colonies);
      return this;
    }

    @Override
    public Colonies build() {
      return new Colonies(this);
    }
  }
}
