// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./messages.proto
package au.com.codeka.common.protobuf;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;

/**
 *
 * Contains a record of (potential) alt accounts for an empire.
 */
public final class EmpireAltAccounts extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_EMPIRE_ID = 0;
  public static final List<EmpireAltEmpire> DEFAULT_ALT_EMPIRE = Collections.emptyList();
  public static final List<DeviceInfo> DEFAULT_DEVICE = Collections.emptyList();

  @ProtoField(tag = 1, type = INT32)
  public Integer empire_id;

  @ProtoField(tag = 2, label = REPEATED, messageType = EmpireAltEmpire.class)
  public List<EmpireAltEmpire> alt_empire;

  @ProtoField(tag = 3, label = REPEATED, messageType = DeviceInfo.class)
  public List<DeviceInfo> device;

  public EmpireAltAccounts() {
  }

  public EmpireAltAccounts(Integer empire_id, List<EmpireAltEmpire> alt_empire, List<DeviceInfo> device) {
    this.empire_id = empire_id;
    this.alt_empire = copyOf(alt_empire);
    this.device = copyOf(device);
  }

  private EmpireAltAccounts(Builder builder) {
    this(builder.empire_id, builder.alt_empire, builder.device);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof EmpireAltAccounts)) return false;
    EmpireAltAccounts o = (EmpireAltAccounts) other;
    return equals(empire_id, o.empire_id)
        && equals(alt_empire, o.alt_empire)
        && equals(device, o.device);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = empire_id != null ? empire_id.hashCode() : 0;
      result = result * 37 + (alt_empire != null ? alt_empire.hashCode() : 1);
      result = result * 37 + (device != null ? device.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<EmpireAltAccounts> {

    public Integer empire_id;
    public List<EmpireAltEmpire> alt_empire;
    public List<DeviceInfo> device;

    public Builder() {
    }

    public Builder(EmpireAltAccounts message) {
      super(message);
      if (message == null) return;
      this.empire_id = message.empire_id;
      this.alt_empire = copyOf(message.alt_empire);
      this.device = copyOf(message.device);
    }

    public Builder empire_id(Integer empire_id) {
      this.empire_id = empire_id;
      return this;
    }

    public Builder alt_empire(List<EmpireAltEmpire> alt_empire) {
      this.alt_empire = checkForNulls(alt_empire);
      return this;
    }

    public Builder device(List<DeviceInfo> device) {
      this.device = checkForNulls(device);
      return this;
    }

    @Override
    public EmpireAltAccounts build() {
      return new EmpireAltAccounts(this);
    }
  }

  public static final class EmpireAltEmpire extends Message {
    private static final long serialVersionUID = 0L;

    public static final Integer DEFAULT_EMPIRE_ID = 0;
    public static final String DEFAULT_EMPIRE_NAME = "";
    public static final String DEFAULT_USER_EMAIL = "";
    public static final Integer DEFAULT_ALLIANCE_ID = 0;

    @ProtoField(tag = 1, type = INT32)
    public Integer empire_id;

    @ProtoField(tag = 2, type = STRING)
    public String empire_name;

    @ProtoField(tag = 3, type = STRING)
    public String user_email;

    @ProtoField(tag = 4, type = INT32)
    public Integer alliance_id;

    public EmpireAltEmpire() {
    }

    public EmpireAltEmpire(Integer empire_id, String empire_name, String user_email, Integer alliance_id) {
      this.empire_id = empire_id;
      this.empire_name = empire_name;
      this.user_email = user_email;
      this.alliance_id = alliance_id;
    }

    private EmpireAltEmpire(Builder builder) {
      this(builder.empire_id, builder.empire_name, builder.user_email, builder.alliance_id);
      setBuilder(builder);
    }

    @Override
    public boolean equals(Object other) {
      if (other == this) return true;
      if (!(other instanceof EmpireAltEmpire)) return false;
      EmpireAltEmpire o = (EmpireAltEmpire) other;
      return equals(empire_id, o.empire_id)
          && equals(empire_name, o.empire_name)
          && equals(user_email, o.user_email)
          && equals(alliance_id, o.alliance_id);
    }

    @Override
    public int hashCode() {
      int result = hashCode;
      if (result == 0) {
        result = empire_id != null ? empire_id.hashCode() : 0;
        result = result * 37 + (empire_name != null ? empire_name.hashCode() : 0);
        result = result * 37 + (user_email != null ? user_email.hashCode() : 0);
        result = result * 37 + (alliance_id != null ? alliance_id.hashCode() : 0);
        hashCode = result;
      }
      return result;
    }

    public static final class Builder extends Message.Builder<EmpireAltEmpire> {

      public Integer empire_id;
      public String empire_name;
      public String user_email;
      public Integer alliance_id;

      public Builder() {
      }

      public Builder(EmpireAltEmpire message) {
        super(message);
        if (message == null) return;
        this.empire_id = message.empire_id;
        this.empire_name = message.empire_name;
        this.user_email = message.user_email;
        this.alliance_id = message.alliance_id;
      }

      public Builder empire_id(Integer empire_id) {
        this.empire_id = empire_id;
        return this;
      }

      public Builder empire_name(String empire_name) {
        this.empire_name = empire_name;
        return this;
      }

      public Builder user_email(String user_email) {
        this.user_email = user_email;
        return this;
      }

      public Builder alliance_id(Integer alliance_id) {
        this.alliance_id = alliance_id;
        return this;
      }

      @Override
      public EmpireAltEmpire build() {
        return new EmpireAltEmpire(this);
      }
    }
  }

  public static final class DeviceInfo extends Message {
    private static final long serialVersionUID = 0L;

    public static final String DEFAULT_DEVICE_ID = "";
    public static final String DEFAULT_DEVICE_MANUFACTURER = "";
    public static final String DEFAULT_DEVICE_MODEL = "";
    public static final String DEFAULT_DEVICE_BUILD = "";
    public static final String DEFAULT_DEVICE_VERSION = "";

    @ProtoField(tag = 1, type = STRING)
    public String device_id;

    @ProtoField(tag = 2, type = STRING)
    public String device_manufacturer;

    @ProtoField(tag = 3, type = STRING)
    public String device_model;

    @ProtoField(tag = 4, type = STRING)
    public String device_build;

    @ProtoField(tag = 5, type = STRING)
    public String device_version;

    public DeviceInfo() {
    }

    public DeviceInfo(String device_id, String device_manufacturer, String device_model, String device_build, String device_version) {
      this.device_id = device_id;
      this.device_manufacturer = device_manufacturer;
      this.device_model = device_model;
      this.device_build = device_build;
      this.device_version = device_version;
    }

    private DeviceInfo(Builder builder) {
      this(builder.device_id, builder.device_manufacturer, builder.device_model, builder.device_build, builder.device_version);
      setBuilder(builder);
    }

    @Override
    public boolean equals(Object other) {
      if (other == this) return true;
      if (!(other instanceof DeviceInfo)) return false;
      DeviceInfo o = (DeviceInfo) other;
      return equals(device_id, o.device_id)
          && equals(device_manufacturer, o.device_manufacturer)
          && equals(device_model, o.device_model)
          && equals(device_build, o.device_build)
          && equals(device_version, o.device_version);
    }

    @Override
    public int hashCode() {
      int result = hashCode;
      if (result == 0) {
        result = device_id != null ? device_id.hashCode() : 0;
        result = result * 37 + (device_manufacturer != null ? device_manufacturer.hashCode() : 0);
        result = result * 37 + (device_model != null ? device_model.hashCode() : 0);
        result = result * 37 + (device_build != null ? device_build.hashCode() : 0);
        result = result * 37 + (device_version != null ? device_version.hashCode() : 0);
        hashCode = result;
      }
      return result;
    }

    public static final class Builder extends Message.Builder<DeviceInfo> {

      public String device_id;
      public String device_manufacturer;
      public String device_model;
      public String device_build;
      public String device_version;

      public Builder() {
      }

      public Builder(DeviceInfo message) {
        super(message);
        if (message == null) return;
        this.device_id = message.device_id;
        this.device_manufacturer = message.device_manufacturer;
        this.device_model = message.device_model;
        this.device_build = message.device_build;
        this.device_version = message.device_version;
      }

      public Builder device_id(String device_id) {
        this.device_id = device_id;
        return this;
      }

      public Builder device_manufacturer(String device_manufacturer) {
        this.device_manufacturer = device_manufacturer;
        return this;
      }

      public Builder device_model(String device_model) {
        this.device_model = device_model;
        return this;
      }

      public Builder device_build(String device_build) {
        this.device_build = device_build;
        return this;
      }

      public Builder device_version(String device_version) {
        this.device_version = device_version;
        return this;
      }

      @Override
      public DeviceInfo build() {
        return new DeviceInfo(this);
      }
    }
  }
}
