// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./messages.proto
package au.com.codeka.common.protobuf;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.STRING;

/**
 *
 * A request to change an empire's shield image. The empire MUST be yourself, and we assume you've already
 * purchased the ability to do it...
 */
public final class EmpireChangeShieldRequest extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_KEY = "";
  public static final ByteString DEFAULT_PNG_IMAGE = ByteString.EMPTY;

  @ProtoField(tag = 1, type = STRING)
  public final String key;

  @ProtoField(tag = 2, type = BYTES)
  public final ByteString png_image;

  @ProtoField(tag = 3)
  public final PurchaseInfo purchase_info;

  public EmpireChangeShieldRequest(String key, ByteString png_image, PurchaseInfo purchase_info) {
    this.key = key;
    this.png_image = png_image;
    this.purchase_info = purchase_info;
  }

  private EmpireChangeShieldRequest(Builder builder) {
    this(builder.key, builder.png_image, builder.purchase_info);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof EmpireChangeShieldRequest)) return false;
    EmpireChangeShieldRequest o = (EmpireChangeShieldRequest) other;
    return equals(key, o.key)
        && equals(png_image, o.png_image)
        && equals(purchase_info, o.purchase_info);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = key != null ? key.hashCode() : 0;
      result = result * 37 + (png_image != null ? png_image.hashCode() : 0);
      result = result * 37 + (purchase_info != null ? purchase_info.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<EmpireChangeShieldRequest> {

    public String key;
    public ByteString png_image;
    public PurchaseInfo purchase_info;

    public Builder() {
    }

    public Builder(EmpireChangeShieldRequest message) {
      super(message);
      if (message == null) return;
      this.key = message.key;
      this.png_image = message.png_image;
      this.purchase_info = message.purchase_info;
    }

    public Builder key(String key) {
      this.key = key;
      return this;
    }

    public Builder png_image(ByteString png_image) {
      this.png_image = png_image;
      return this;
    }

    public Builder purchase_info(PurchaseInfo purchase_info) {
      this.purchase_info = purchase_info;
      return this;
    }

    @Override
    public EmpireChangeShieldRequest build() {
      return new EmpireChangeShieldRequest(this);
    }
  }
}
