// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./messages.proto
package au.com.codeka.common.protobuf;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;

/**
 *
 * The "hello" request when you first join the game contains some info about yourself which we
 * record for posterity.
 */
public final class HelloRequest extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_DEVICE_MODEL = "";
  public static final String DEFAULT_DEVICE_MANUFACTURER = "";
  public static final String DEFAULT_DEVICE_BUILD = "";
  public static final String DEFAULT_DEVICE_VERSION = "";
  public static final Integer DEFAULT_MEMORY_CLASS = 0;
  public static final Boolean DEFAULT_ALLOW_INLINE_NOTFICATIONS = false;
  public static final Boolean DEFAULT_NO_STAR_LIST = false;

  /**
   * The value of android.os.Build.MODEL for this device
   */
  @ProtoField(tag = 1, type = STRING)
  public final String device_model;

  /**
   * The value of android.os.Build.MANUFACTURER for this device
   */
  @ProtoField(tag = 2, type = STRING)
  public final String device_manufacturer;

  /**
   * The value of android.os.Build.DISPLAY for this device
   */
  @ProtoField(tag = 3, type = STRING)
  public final String device_build;

  /**
   * The value of android.os.Build.VERSION.RELEASE for this device (note that this can
   * change if you upgrade the OS without re-registering your device!)
   */
  @ProtoField(tag = 4, type = STRING)
  public final String device_version;

  /**
   * The memory class of your device -- basically, how much memory can we assume is available
   * to the War Worlds app (in megabytes)
   */
  @ProtoField(tag = 5, type = INT32)
  public final Integer memory_class;

  /**
   * If present and set to true, we'll occasionally respond to requests with a protocol buffer
   * wrapped in a NotficationWrapper message. This way, we can get notifications without having
   * to wait for GCM.
   */
  @ProtoField(tag = 6, type = BOOL)
  public final Boolean allow_inline_notfications;

  /**
   * If true, we'll NOT return the list of star_ids that you own. Newer clients don't need
   * it anymore, and it just wastes time/resources returning it.
   */
  @ProtoField(tag = 7, type = BOOL)
  public final Boolean no_star_list;

  public HelloRequest(String device_model, String device_manufacturer, String device_build, String device_version, Integer memory_class, Boolean allow_inline_notfications, Boolean no_star_list) {
    this.device_model = device_model;
    this.device_manufacturer = device_manufacturer;
    this.device_build = device_build;
    this.device_version = device_version;
    this.memory_class = memory_class;
    this.allow_inline_notfications = allow_inline_notfications;
    this.no_star_list = no_star_list;
  }

  private HelloRequest(Builder builder) {
    this(builder.device_model, builder.device_manufacturer, builder.device_build, builder.device_version, builder.memory_class, builder.allow_inline_notfications, builder.no_star_list);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof HelloRequest)) return false;
    HelloRequest o = (HelloRequest) other;
    return equals(device_model, o.device_model)
        && equals(device_manufacturer, o.device_manufacturer)
        && equals(device_build, o.device_build)
        && equals(device_version, o.device_version)
        && equals(memory_class, o.memory_class)
        && equals(allow_inline_notfications, o.allow_inline_notfications)
        && equals(no_star_list, o.no_star_list);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = device_model != null ? device_model.hashCode() : 0;
      result = result * 37 + (device_manufacturer != null ? device_manufacturer.hashCode() : 0);
      result = result * 37 + (device_build != null ? device_build.hashCode() : 0);
      result = result * 37 + (device_version != null ? device_version.hashCode() : 0);
      result = result * 37 + (memory_class != null ? memory_class.hashCode() : 0);
      result = result * 37 + (allow_inline_notfications != null ? allow_inline_notfications.hashCode() : 0);
      result = result * 37 + (no_star_list != null ? no_star_list.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<HelloRequest> {

    public String device_model;
    public String device_manufacturer;
    public String device_build;
    public String device_version;
    public Integer memory_class;
    public Boolean allow_inline_notfications;
    public Boolean no_star_list;

    public Builder() {
    }

    public Builder(HelloRequest message) {
      super(message);
      if (message == null) return;
      this.device_model = message.device_model;
      this.device_manufacturer = message.device_manufacturer;
      this.device_build = message.device_build;
      this.device_version = message.device_version;
      this.memory_class = message.memory_class;
      this.allow_inline_notfications = message.allow_inline_notfications;
      this.no_star_list = message.no_star_list;
    }

    /**
     * The value of android.os.Build.MODEL for this device
     */
    public Builder device_model(String device_model) {
      this.device_model = device_model;
      return this;
    }

    /**
     * The value of android.os.Build.MANUFACTURER for this device
     */
    public Builder device_manufacturer(String device_manufacturer) {
      this.device_manufacturer = device_manufacturer;
      return this;
    }

    /**
     * The value of android.os.Build.DISPLAY for this device
     */
    public Builder device_build(String device_build) {
      this.device_build = device_build;
      return this;
    }

    /**
     * The value of android.os.Build.VERSION.RELEASE for this device (note that this can
     * change if you upgrade the OS without re-registering your device!)
     */
    public Builder device_version(String device_version) {
      this.device_version = device_version;
      return this;
    }

    /**
     * The memory class of your device -- basically, how much memory can we assume is available
     * to the War Worlds app (in megabytes)
     */
    public Builder memory_class(Integer memory_class) {
      this.memory_class = memory_class;
      return this;
    }

    /**
     * If present and set to true, we'll occasionally respond to requests with a protocol buffer
     * wrapped in a NotficationWrapper message. This way, we can get notifications without having
     * to wait for GCM.
     */
    public Builder allow_inline_notfications(Boolean allow_inline_notfications) {
      this.allow_inline_notfications = allow_inline_notfications;
      return this;
    }

    /**
     * If true, we'll NOT return the list of star_ids that you own. Newer clients don't need
     * it anymore, and it just wastes time/resources returning it.
     */
    public Builder no_star_list(Boolean no_star_list) {
      this.no_star_list = no_star_list;
      return this;
    }

    @Override
    public HelloRequest build() {
      return new HelloRequest(this);
    }
  }
}
