// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: stats.proto at 6:1
package au.com.codeka.warworlds.server.proto;

import au.com.codeka.warworlds.common.proto.DeviceInfo;
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class LoginEvent extends Message<LoginEvent, LoginEvent.Builder> {
  public static final ProtoAdapter<LoginEvent> ADAPTER = new ProtoAdapter_LoginEvent();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_TIMESTAMP = 0L;

  public static final Integer DEFAULT_DAY = 0;

  public static final Long DEFAULT_EMPIRE_ID = 0L;

  public static final String DEFAULT_EMAIL_ADDR = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long timestamp;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer day;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long empire_id;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String email_addr;

  @WireField(
      tag = 5,
      adapter = "au.com.codeka.warworlds.common.proto.DeviceInfo#ADAPTER"
  )
  public final DeviceInfo device_info;

  public LoginEvent(Long timestamp, Integer day, Long empire_id, String email_addr, DeviceInfo device_info) {
    this(timestamp, day, empire_id, email_addr, device_info, ByteString.EMPTY);
  }

  public LoginEvent(Long timestamp, Integer day, Long empire_id, String email_addr, DeviceInfo device_info, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.timestamp = timestamp;
    this.day = day;
    this.empire_id = empire_id;
    this.email_addr = email_addr;
    this.device_info = device_info;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.timestamp = timestamp;
    builder.day = day;
    builder.empire_id = empire_id;
    builder.email_addr = email_addr;
    builder.device_info = device_info;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LoginEvent)) return false;
    LoginEvent o = (LoginEvent) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(timestamp, o.timestamp)
        && Internal.equals(day, o.day)
        && Internal.equals(empire_id, o.empire_id)
        && Internal.equals(email_addr, o.email_addr)
        && Internal.equals(device_info, o.device_info);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (timestamp != null ? timestamp.hashCode() : 0);
      result = result * 37 + (day != null ? day.hashCode() : 0);
      result = result * 37 + (empire_id != null ? empire_id.hashCode() : 0);
      result = result * 37 + (email_addr != null ? email_addr.hashCode() : 0);
      result = result * 37 + (device_info != null ? device_info.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (timestamp != null) builder.append(", timestamp=").append(timestamp);
    if (day != null) builder.append(", day=").append(day);
    if (empire_id != null) builder.append(", empire_id=").append(empire_id);
    if (email_addr != null) builder.append(", email_addr=").append(email_addr);
    if (device_info != null) builder.append(", device_info=").append(device_info);
    return builder.replace(0, 2, "LoginEvent{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<LoginEvent, Builder> {
    public Long timestamp;

    public Integer day;

    public Long empire_id;

    public String email_addr;

    public DeviceInfo device_info;

    public Builder() {
    }

    public Builder timestamp(Long timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    public Builder day(Integer day) {
      this.day = day;
      return this;
    }

    public Builder empire_id(Long empire_id) {
      this.empire_id = empire_id;
      return this;
    }

    public Builder email_addr(String email_addr) {
      this.email_addr = email_addr;
      return this;
    }

    public Builder device_info(DeviceInfo device_info) {
      this.device_info = device_info;
      return this;
    }

    @Override
    public LoginEvent build() {
      return new LoginEvent(timestamp, day, empire_id, email_addr, device_info, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_LoginEvent extends ProtoAdapter<LoginEvent> {
    ProtoAdapter_LoginEvent() {
      super(FieldEncoding.LENGTH_DELIMITED, LoginEvent.class);
    }

    @Override
    public int encodedSize(LoginEvent value) {
      return (value.timestamp != null ? ProtoAdapter.INT64.encodedSizeWithTag(1, value.timestamp) : 0)
          + (value.day != null ? ProtoAdapter.INT32.encodedSizeWithTag(2, value.day) : 0)
          + (value.empire_id != null ? ProtoAdapter.INT64.encodedSizeWithTag(3, value.empire_id) : 0)
          + (value.email_addr != null ? ProtoAdapter.STRING.encodedSizeWithTag(4, value.email_addr) : 0)
          + (value.device_info != null ? DeviceInfo.ADAPTER.encodedSizeWithTag(5, value.device_info) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, LoginEvent value) throws IOException {
      if (value.timestamp != null) ProtoAdapter.INT64.encodeWithTag(writer, 1, value.timestamp);
      if (value.day != null) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.day);
      if (value.empire_id != null) ProtoAdapter.INT64.encodeWithTag(writer, 3, value.empire_id);
      if (value.email_addr != null) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.email_addr);
      if (value.device_info != null) DeviceInfo.ADAPTER.encodeWithTag(writer, 5, value.device_info);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public LoginEvent decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.timestamp(ProtoAdapter.INT64.decode(reader)); break;
          case 2: builder.day(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.empire_id(ProtoAdapter.INT64.decode(reader)); break;
          case 4: builder.email_addr(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.device_info(DeviceInfo.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public LoginEvent redact(LoginEvent value) {
      Builder builder = value.newBuilder();
      if (builder.device_info != null) builder.device_info = DeviceInfo.ADAPTER.redact(builder.device_info);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
