// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: suspicious_event.proto at 6:1
package au.com.codeka.warworlds.server.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * A suspicious event is something we record when a client sends us something that we don't expect.
 * It could be an early indication of attempted cheating, or bugs in the client or something else.
 */
public final class SuspiciousEvent extends Message<SuspiciousEvent, SuspiciousEvent.Builder> {
  public static final ProtoAdapter<SuspiciousEvent> ADAPTER = new ProtoAdapter_SuspiciousEvent();

  private static final long serialVersionUID = 0L;

  public SuspiciousEvent() {
    this(ByteString.EMPTY);
  }

  public SuspiciousEvent(ByteString unknownFields) {
    super(ADAPTER, unknownFields);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof SuspiciousEvent;
  }

  @Override
  public int hashCode() {
    return unknownFields().hashCode();
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    return builder.replace(0, 2, "SuspiciousEvent{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<SuspiciousEvent, Builder> {
    public Builder() {
    }

    @Override
    public SuspiciousEvent build() {
      return new SuspiciousEvent(buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_SuspiciousEvent extends ProtoAdapter<SuspiciousEvent> {
    ProtoAdapter_SuspiciousEvent() {
      super(FieldEncoding.LENGTH_DELIMITED, SuspiciousEvent.class);
    }

    @Override
    public int encodedSize(SuspiciousEvent value) {
      return value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, SuspiciousEvent value) throws IOException {
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public SuspiciousEvent decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public SuspiciousEvent redact(SuspiciousEvent value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
