// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: account.proto at 16:1
package au.com.codeka.warworlds.common.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * This is the account object that's stored in the data store. It links to your empire and other
 * details about your account.
 */
public final class Account extends Message<Account, Account.Builder> {
  public static final ProtoAdapter<Account> ADAPTER = new ProtoAdapter_Account();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_EMPIRE_ID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long empire_id;

  public Account(Long empire_id) {
    this(empire_id, ByteString.EMPTY);
  }

  public Account(Long empire_id, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.empire_id = empire_id;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.empire_id = empire_id;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Account)) return false;
    Account o = (Account) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(empire_id, o.empire_id);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (empire_id != null ? empire_id.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (empire_id != null) builder.append(", empire_id=").append(empire_id);
    return builder.replace(0, 2, "Account{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Account, Builder> {
    public Long empire_id;

    public Builder() {
    }

    public Builder empire_id(Long empire_id) {
      this.empire_id = empire_id;
      return this;
    }

    @Override
    public Account build() {
      return new Account(empire_id, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Account extends ProtoAdapter<Account> {
    ProtoAdapter_Account() {
      super(FieldEncoding.LENGTH_DELIMITED, Account.class);
    }

    @Override
    public int encodedSize(Account value) {
      return (value.empire_id != null ? ProtoAdapter.INT64.encodedSizeWithTag(1, value.empire_id) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, Account value) throws IOException {
      if (value.empire_id != null) ProtoAdapter.INT64.encodeWithTag(writer, 1, value.empire_id);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Account decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.empire_id(ProtoAdapter.INT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public Account redact(Account value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
