// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: admin.proto at 6:1
package au.com.codeka.warworlds.common.proto;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

/**
 * The role an AdminUser has in the backend.
 */
public enum AdminRole implements WireEnum {
  /**
   * The administrator role allows you to modify the security settings of the backend.
   */
  ADMINISTRATOR(1),

  /**
   * A role which allows you to modify/view the starfield.
   */
  STARFIELD(2),

  /**
   * A role which allows you to modify empires.
   */
  EMPIRE(3),

  /**
   * A role which allows you to monitor chat and sinbin users, etc.
   */
  CHAT(4);

  public static final ProtoAdapter<AdminRole> ADAPTER = ProtoAdapter.newEnumAdapter(AdminRole.class);

  private final int value;

  AdminRole(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static AdminRole fromValue(int value) {
    switch (value) {
      case 1: return ADMINISTRATOR;
      case 2: return STARFIELD;
      case 3: return EMPIRE;
      case 4: return CHAT;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
