// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: star.proto at 34:1
package au.com.codeka.warworlds.common.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * An array of (x,y) coordinates. This is used to store the list of empty sectors, as well
 * as a list of "to-be-generated" sectors.
 */
public final class SectorCoordArray extends Message<SectorCoordArray, SectorCoordArray.Builder> {
  public static final ProtoAdapter<SectorCoordArray> ADAPTER = new ProtoAdapter_SectorCoordArray();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "au.com.codeka.warworlds.common.proto.SectorCoord#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<SectorCoord> coords;

  public SectorCoordArray(List<SectorCoord> coords) {
    this(coords, ByteString.EMPTY);
  }

  public SectorCoordArray(List<SectorCoord> coords, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.coords = Internal.immutableCopyOf("coords", coords);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.coords = Internal.copyOf("coords", coords);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SectorCoordArray)) return false;
    SectorCoordArray o = (SectorCoordArray) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(coords, o.coords);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (coords != null ? coords.hashCode() : 1);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (coords != null) builder.append(", coords=").append(coords);
    return builder.replace(0, 2, "SectorCoordArray{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<SectorCoordArray, Builder> {
    public List<SectorCoord> coords;

    public Builder() {
      coords = Internal.newMutableList();
    }

    public Builder coords(List<SectorCoord> coords) {
      Internal.checkElementsNotNull(coords);
      this.coords = coords;
      return this;
    }

    @Override
    public SectorCoordArray build() {
      return new SectorCoordArray(coords, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_SectorCoordArray extends ProtoAdapter<SectorCoordArray> {
    ProtoAdapter_SectorCoordArray() {
      super(FieldEncoding.LENGTH_DELIMITED, SectorCoordArray.class);
    }

    @Override
    public int encodedSize(SectorCoordArray value) {
      return SectorCoord.ADAPTER.asRepeated().encodedSizeWithTag(1, value.coords)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, SectorCoordArray value) throws IOException {
      if (value.coords != null) SectorCoord.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.coords);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public SectorCoordArray decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.coords.add(SectorCoord.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public SectorCoordArray redact(SectorCoordArray value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.coords, SectorCoord.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
