package au.com.codeka.warworlds.server.ctrl;

import java.sql.Statement;

import au.com.codeka.warworlds.server.RequestException;
import au.com.codeka.warworlds.server.data.DB;
import au.com.codeka.warworlds.server.data.SqlStmt;
import au.com.codeka.warworlds.server.data.Transaction;
import au.com.codeka.warworlds.server.model.BuildRequest;

public class BuildQueueController {
    public void build(BuildRequest buildRequest) throws RequestException {
        try (Transaction t = DB.beginTransaction()) {
            //Star star = new StarController(t).getStar(buildRequest.getStarID());

            // TODO: check dependencies
            // TODO: check build limits

            if (buildRequest.getCount() > 5000) {
                buildRequest.setCount(5000);
            }

            SqlStmt stmt = t.prepare("INSERT INTO build_requests (star_id, planet_index, colony_id, empire_id," +
                                       " existing_building_id, design_kind, design_id," +
                                       " count, progress, start_time, end_time)" +
                                    " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                                    Statement.RETURN_GENERATED_KEYS);
            stmt.setInt(1, buildRequest.getStarID());
            stmt.setInt(2, buildRequest.getPlanetIndex());
            stmt.setInt(3, buildRequest.getColonyID());
            stmt.setInt(4, buildRequest.getEmpireID());
            if (buildRequest.getExistingBuildingKey() != null) {
                stmt.setInt(5, buildRequest.getExistingBuildingID());
            } else {
                stmt.setNull(5);
            }
            stmt.setInt(6, buildRequest.getDesignKind().getValue());
            stmt.setString(7, buildRequest.getDesignID());
            stmt.setInt(8, buildRequest.getCount());
            stmt.setDouble(9, buildRequest.getProgress(false));
            stmt.setDateTime(10, buildRequest.getStartTime());
            stmt.setDateTime(11, buildRequest.getEndTime());
            stmt.update();
            buildRequest.setID(stmt.getAutoGeneratedID());

            t.commit();
        } catch(Exception e) {
            throw new RequestException(500, e);
        }
    }
}
